---

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    container_name: frontend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    container_name: backend
